### ISSUE TITLE
Shortcuts don't work in the latest Anki version

### ISSUE THREAD

**Issue by stiansci** [abdnh/anki-control-audio-playback#2]

**Comment by abdnh** [comment]
All shortcuts work for me on 2.1.65. Do you perhaps have a non-English keyboard layout active?

**Comment by stiansci** [comment]
Hi, I have an Italian keyboard layout indeed.

**Comment by abdnh** [comment]
That should be it. Shortcuts are layout-dependent. You can change the shortcuts from the config if their positions are not comfortable in your Italian layout. Let me know if that still doesn't work.

**Comment by stiansci** [comment]
Changing the shortcuts solved the issue. I tried to use numbers as shortcuts but they didn't work. Using other keys worked for some reason.
